---
- name: Install Calico operator CRDs
  kubernetes.core.k8s:
    state: present
    src: "https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/operator-crds.yaml"
    wait: true
    kubeconfig: "/home/{{ k8s_user }}/.kube/config"

- name: Install tigera operator
  kubernetes.core.k8s:
    state: present
    src: "https://raw.githubusercontent.com/projectcalico/calico/v{{ calico_version }}/manifests/tigera-operator.yaml"
    wait: true
    kubeconfig: "/home/{{ k8s_user }}/.kube/config"

- name: Customize Calico configuration
  template:
    src: custom-resources.j2
    dest: "/tmp/custom-resources.yaml"

- name: Install custom resources
  kubernetes.core.k8s:
    state: present
    src: "/tmp/custom-resources.yaml"
    kubeconfig: "/home/{{ k8s_user }}/.kube/config"