---
- name: Install Calico operator CRDs
  kubernetes.core.k8s:
    state: present
    src: "https://raw.githubusercontent.com/projectcalico/calico/v3.30.4/manifests/operator-crds.yaml"
    kubeconfig: "/home/{{ k8s_user }}/.kube/config"
    wait: true
    wait_condition:
      type: "Available"  # Тип условия
      status: "True"     # Статус условия


- name: Install tigera operator
  kubernetes.core.k8s:
    state: present
    src: "https://raw.githubusercontent.com/projectcalico/calico/v3.30.4/manifests/tigera-operator.yaml"
    wait: true
    kubeconfig: "/home/{{ k8s_user }}/.kube/config"

- name: Customize Calico configuration
  template:
    src: custom-resources.j2
    dest: "/tmp/custom-resources.yaml"

- name: Install custom resources
  kubernetes.core.k8s:
    state: present
    src: "/tmp/custom-resources.yaml"
    kubeconfig: "/home/{{ k8s_user }}/.kube/config"