---
- name: Check if node is already part of cluster
  environment:
    KUBECONFIG: "/home/{{ k8s_user }}/.kube/config"
  command: kubectl get node {{ inventory_hostname }}
  register: node_check
  delegate_to: "{{ groups['mgm'][0] }}"
  failed_when: false
  changed_when: false
  when: "'wrk' in group_names"

- name: Get join command from master
  environment:
    KUBECONFIG: "/home/{{ k8s_user }}/.kube/config"
  command: kubeadm token create --print-join-command
  register: join_command
  delegate_to: "{{ groups['mgm'][0] }}"
  run_once: true
  when: 
    - "'wrk' in group_names"
    - node_check.rc != 0

- name: Check if kubelet is already active on worker
  systemd:
    name: kubelet
  register: kubelet_service
  changed_when: false
  when: "'wrk' in group_names"

- name: Join worker nodes to cluster
  command: "{{ hostvars[groups['mgm'][0]]['join_command']['stdout'] }}"
  when: 
    - "'wrk' in group_names"
    - kubelet_service.status.ActiveState == 'active'
    - hostvars[groups['mgm'][0]]['join_command'] is defined
    - node_check.rc != 0