---
- name: Get join command from master
  delegate_to: "{{ groups['mgm'][0] }}"
  run_once: true
  environment:
    KUBECONFIG: "/home/{{ k8s_user }}/.kube/config"
  command: kubeadm token create --print-join-command
  register: join_command

- name: deb
  debug:
    msg: "{{ join_command.stdout_lines }}"

#- name: Join worker nodes to cluster
#  command: "{{ join_command.results[0].stdout }}"
#  when: inventory_hostname in groups['wrk']