---
- name: Get join command from master
  environment:
    KUBECONFIG: "/home/{{ k8s_user }}/.kube/config"
  command: kubeadm token create --print-join-command
  register: join_command
  when: "'mgm' in group_names"

- name: Join worker nodes to cluster
#  command: "{{ join_command }}"
  debug:
    msg: "{{ join_command_result }}"
  when: 
    - "'wrk' in group_names"
    - join_command is defined