---
- name: Get join command from master
  environment:
    KUBECONFIG: "/home/{{ k8s_user }}/.kube/config"
  command: kubeadm token create --print-join-command
  register: join_command
  delegate_to: "{{ groups['mgm'][0] }}"
  run_once: true

- name: Debug join command
  debug:
    msg: "Join command: {{ join_command.stdout }}"
  when: "'mgm' in group_names"