---
- name: Check for existing Kubernetes config
  stat:
    path: /etc/kubernetes/admin.conf
  register: kube_config

- name: Skip master initialization
  debug:
    msg: "Skipping master initialization - Kubernetes cluster already exists"
  when: kube_config.stat.exists

- name: Initialize Kubernetes cluster
  block:
    - name: Initialize Kubernetes cluster
      command: kubeadm init --pod-network-cidr={{ pod_network_cidr }}
      register: kubeadm_init

    - name: Create .kube directory
      file:
        path: "/home/{{ k8s_user }}/.kube"
        state: directory
        mode: '0755'
        owner: "{{ k8s_user }}"
        group: "{{ k8s_user }}"

    - name: Copy admin config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ k8s_user }}/.kube/config"
        remote_src: yes
        owner: "{{ k8s_user }}"
        group: "{{ k8s_user }}"
        mode: '0600'

    - name: Install Calico operator CRDs
      community.kubernetes.k8s:
        state: present
        src: "https://raw.githubusercontent.com/projectcalico/calico/v3.30.4/manifests/operator-crds.yaml"

    - name: Install tigera operator
      community.kubernetes.k8s:
        state: present
        src: "https://raw.githubusercontent.com/projectcalico/calico/v3.30.4/manifests/tigera-operator.yaml"

    - name: Customize Calico configuration
      template:
        src: custom-resources.j2
        dest: "/tmp/custom-resources.yaml"

    - name: Install custom resources
      community.kubernetes.k8s:
        state: present
        src: "/tmp/custom-resources.yaml"

  when: not kube_config.stat.exists