---
- name: Check for existing Kubernetes config
  stat:
    path: /etc/kubernetes/admin.conf
  register: kube_config

- name: Skip master initialization
  debug:
    msg: "kubeadm init --pod-network-cidr={{ pod_network_cidr }} --image-repository={{ container_registry }}"

- name: Initialize Kubernetes cluster
  block:
    - name: Initialize Kubernetes cluster
      command: kubeadm init --pod-network-cidr={{ pod_network_cidr }} --image-repository={{ container_registry }}
      register: kubeadm_init

    - name: Create .kube directory
      file:
        path: "/home/{{ k8s_user }}/.kube"
        state: directory
        mode: '0755'
        owner: "{{ k8s_user }}"
        group: "{{ k8s_user }}"

    - name: Copy admin config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ k8s_user }}/.kube/config"
        remote_src: yes
        owner: "{{ k8s_user }}"
        group: "{{ k8s_user }}"
        mode: '0600'

  when: not kube_config.stat.exists