---
k8s_user: "us"
kubernetes_version: "1.34"
pod_network_cidr: "192.168.0.0/16"
container_registry: "registry.aliyuncs.com/google_containers"
calico_version: "3.30.4"
calico_encapsulation: "VXLANCrossSubnet"